from abc import ABC, abstractmethod
from collections.abc import Callable, Sequence


class CompositorWorkspace(ABC):
    @property
    @abstractmethod
    def name(self) -> str: ...
    @property
    @abstractmethod
    def id(self) -> int: ...
    @property
    @abstractmethod
    def active(self) -> bool: ...


class CompositorWindow(ABC):
    @property
    @abstractmethod
    def id(self) -> int: ...
    @property
    @abstractmethod
    def title(self) -> str: ...
    @property
    @abstractmethod
    def app_id(self) -> str: ...
    @property
    @abstractmethod
    def focused(self) -> bool: ...
    @property
    @abstractmethod
    def workspace_id(self) -> int: ...


class CompositorMonitor(ABC):
    @property
    @abstractmethod
    def id(self) -> int: ...
    @property
    @abstractmethod
    def name(self) -> str: ...
    @property
    @abstractmethod
    def active(self) -> bool: ...
    @property
    @abstractmethod
    def width(self) -> int: ...
    @property
    @abstractmethod
    def height(self) -> int: ...
    @property
    @abstractmethod
    def x(self) -> int: ...
    @property
    @abstractmethod
    def y(self) -> int: ...
    @property
    @abstractmethod
    def primary(self) -> bool: ...
    @property
    @abstractmethod
    def connection(self) -> str: ...
    @property
    @abstractmethod
    def rotation(self) -> int: ...
    @property
    @abstractmethod
    def scale(self) -> float: ...
    @property
    @abstractmethod
    def workspaces(self) -> Sequence[CompositorWorkspace]: ...
    @property
    @abstractmethod
    def windows(self) -> Sequence[CompositorWindow]: ...
    @property
    @abstractmethod
    def active_workspace(self) -> CompositorWorkspace: ...
    @property
    @abstractmethod
    def active_window(self) -> CompositorWindow: ...


class CompositorInterface(ABC):
    @property
    @abstractmethod
    def compositor_name(self) -> str: ...
    @abstractmethod
    def is_available(self) -> bool: ...
    @abstractmethod
    def workspaces(self) -> Sequence[CompositorWorkspace]: ...
    @abstractmethod
    def switch_to_workspace(self, _id: int) -> None: ...
    @abstractmethod
    def windows(self) -> Sequence[CompositorWindow]: ...
    @abstractmethod
    def focus_window(self, window_id: int) -> None: ...
    @abstractmethod
    def close_window(self, window_id: int) -> None: ...
    @abstractmethod
    def monitors(self) -> Sequence[CompositorMonitor]: ...
    @abstractmethod
    def active_monitor(self) -> CompositorMonitor: ...
    @property
    @abstractmethod
    def active_keyboard_layout(self) -> str: ...
    @abstractmethod
    def on_workspace_changed(self, callback: Callable) -> None: ...
    @abstractmethod
    def on_window_focused(self, callback: Callable) -> None: ...
    @abstractmethod
    def on_layout_changed(self, callback: Callable) -> None: ...
